### ISSUE TITLE
Petit glitch 

### ISSUE THREAD

**Issue by dsaingre** [Errorname/Lost-in-Warehouse#1]
![capture du 2016-01-16 17 50 28](https://cloud.githubusercontent.com/assets/7606929/12373449/d0766c98-bc79-11e5-9f96-881844e48858.png)

Petit glitch : possibilité de passer sous les dalles vertes dans le niveau 5

**Comment by Errorname** [comment]
J'ai réussi à reproduire.

Après quelques tests, il s'avère que ce glitch est présent sur les portes "inversé" (ouverte quand trigger non appuyé).

Reste à trouver le bug...

**Comment by Errorname** [comment]
Il s'agissait d'une erreur de frappe!

Merci d'avoir prévenu ;)

**Comment by dsaingre** [comment]
De rien c'est normal ;)
